"""Backward-compatibility shim — all tools moved to src.tools.marketing package."""

from src.tools.marketing import (  # noqa: F401
    create_weekly_plan,
    get_plans,
    get_plan,
    update_plan_status,
    update_post_in_plan,
    add_post_to_plan,
    remove_post_from_plan,
    get_todays_posts,
    save_instagram_post,
    get_instagram_posts,
    get_post_by_instagram_id,
    save_youtube_video,
    get_youtube_videos,
    get_youtube_video_by_id,
    get_marketing_memory,
    update_marketing_memory,
    schedule_retry_job,
    get_admin_notes,
    add_admin_note,
    remove_admin_note,
    compact_marketing_memory,
    clear_marketing_memory,
    get_marketing_tools,
    get_admin_tools,
)
